export const GET_PROFILE = 'GET_PROFILE';
export const SET_USER = 'SET_USER';
export const SET_IMG = 'SET_IMG';
export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';
export const GET_CAT = 'GET_CAT';

export const SET_CAT = 'SET_CAT';
export const GET_ALL_BARTERS = 'GET_ALL_BARTERS'

export const ACCEPT_BARTER = 'ACCEPT_BARTER'
export const GET_ALL_ACTIVE_BARTERS = 'GET_ALL_ACTIVE_BARTERS'

export const DECLINE_BARTER = 'DECLINE_BARTER'
export const ALL_USER_PORTFOLIO = 'ALL_USER_PORTFOLIO'
export const GET_PORTFOLIO = 'GET_PORTFOLIO'
export const GET_ALL_DECLINE_BARTERS = 'GET_ALL_DECLINE_BARTERS'
export const DELETE_DECLINE_BARTERS = 'DELETE_DECLINE_BARTERS'
export const USER_REGISTER = 'USER_REGISTER'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const GET_ALL_CAT = 'GET_ALL_CAT';
export const GET_USER_TAGS = 'USER_TAGS';


export const END_BARTER = 'END_BARTER'
export const GET_ALL_ENDED_BARTERS = 'GET_ALL_ENDED_BARTERS'



export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const GET_PROFILE_FOR_CATEGORIES = 'GET_PROFILE_FOR_CATEGORIES'
